### PR TITLE
fix: issue on generating graph

### LINKED ISSUE #105: frontend:generate graph from node topology is broken

### PR DESCRIPTION
**Pull request by 0tuedon**
Thi PR closes #105 on the generate graph bug (button)

### CODE REVIEW

File: frontend/src/helpers/generate-graphml.ts [hunk 1]
```diff
@@ -60,25 +61,25 @@ const generateGraphML = ({ nodes, edges }: GraphElement) => {
...
-            target: edge.target.id,
+            id: edge.source,
+            source: edge.source,
+            target: edge.target,
           },
-          data: [
-            { "@": { key: "edgelabel" }, "#": edge.source.name },
-            { "@": { key: "weight" }, "#": edge.source.size },
-          ],
+          // data: [
```
Comment (Extheoisah) [inline frontend/src/helpers/generate-graphml.ts]: Lets remove this if we ain't using it

**Review by Extheoisah — CHANGES_REQUESTED** [review]

File: frontend/src/helpers/generate-graphml.ts (hunk 1 above)
Comment (0tuedon) [reply frontend/src/helpers/generate-graphml.ts]: Alright, updated the repo to this change
